# Target directory to copy
path: "./example/example-app"

# Not supported yet: git url
git: "github.com/path/to/repo"

# Optional message to user
# Default is "Copying {path}"
message: "Copying example-app"

# Changes to apply to copied files
changes:
  # Helper message about change
  "Project prefix":
    # Replace this token
    replace: "example"
    # With optional default value
    default: "myexample"

  "App name":
    replace: "app"
    default: "myapp"

# Not supported yet: Change file and directory names too, not just the content
changefilenames: true