# Target directory to copy
path: "./example/example-app"

# Not supported yet: git url
git: "github.com/jan25/makecopy"

# Optional message to user
# Default is "Copying {path}"
message: "Copying example-app"

# Changes to apply to copied files
changes:
  # Helper message about change
  "Project prefix":
    # Replace this token
    replace: "example"
    # Replace with this token
    default: "myexample"

  "App name":
    replace: "app"
    default: "myapp"

# Not supported yet: Change file and directory names too, not just the content
changefilenames: true